config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/pages/news' =>'pages#news'
  get '/pages/aboutus' =>'pages#aboutus'
  get '/pages/contact' =>'pages#contact'
  get '/pages/disclaimer' =>'pages#disclaimer'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, except: [ :delete ] do
    resources :events, except: [ :index ]
    resources :reviews, except: [ :index ] do
      resources :comments, except: [ :index ]
    end
    resources :comments, only: [ :index ]
  end

  #get '/users/:id/edit_schedule' =>'users#edit_schedule', as: :edit_schedule
  #patch '/users/:id/edit_schedule'=>'users#edit_schedule'

  resources :reviews, only: [ :index ]
  resources :events, only: [ :index ]
  # resources :comments, only: [ :index ]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
    <div class="links">
      <a href="https://t.co/TCmg4dj3E0" target="_blank"><i class="fab fa-fw fa-discord"></i></a>
      <a href="https://steamcommunity.com/groups/HLLJapan" target="_blank"><i class="fab fa-fw fa-steam"></i></a>
      <a href="https://twitter.com/HLL_JPN" target="_blank"><i class="fab fa-fw fa-twitter"></i></a>
      <p>このホームページのスポンサーと作成者は匿名です。</p>
      <%= link_to "免責事項", pages_disclaimer_path, style: 'color: white; font-size: 18px;' %>
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "" do %>
    <%= image_tag "https://cdn.discordapp.com/attachments/812567934551457805/813051684212310036/HLL.png", class: "avatar-large"%>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <div class="topnav", style: >
    <%= link_to "ホーム", root_path, class: "nav-link", style: 'color: white;' %>
    <%= link_to "ニュース", pages_news_path, class: "nav-link", style: 'color: white;' %>
    <%= link_to "HLL Wiki", reviews_path, class: "nav-link", style: 'color: white;' %>
    <%= link_to "イベント", events_path, class: "nav-link", style: 'color: white;' %>
    <%= link_to "メンバー", users_path, class: "nav-link", style: 'color: white;' %>
    <%= link_to "コンタクト", pages_contact_path, class: "nav-link", style: 'color: white;' %>
    <%= link_to "About Us", pages_aboutus_path, class: "nav-link", style: 'color: white;' %>
    </div>
      <% if user_signed_in? %>
        <!-- 
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        -->
        <li class="nav-item dropdown">
          <% if current_user.nil? || current_user.avatar.nil? %>
            <%= image_tag "https://cdn.discordapp.com/attachments/812567934551457805/813051684212310036/HLL.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <% if current_user.avatar.attached? == true %>
             <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://cdn.discordapp.com/attachments/812567934551457805/813051684212310036/HLL.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "プロファイル", user_path(current_user.id), class: "dropdown-item" %>
            <%= link_to "編集", edit_user_path(current_user.id), class: "dropdown-item" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
      <div class="nav-li-side">
        <li class="nav-item">
          <%= link_to "ログイン", new_user_session_path, class: "nav-link", style: 'color: white;' %>
        </li>
      </div>
      <% end %>
    </ul>
  </div>
</div>