config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/pages/news' =>'pages#news'
  get '/pages/aboutus' =>'pages#aboutus'
  get '/pages/contact' =>'pages#contact'
  get '/pages/disclaimer' =>'pages#disclaimer'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, except: [ :delete ] do
    resources :events, except: [ :index ]
    resources :reviews, except: [ :index ] do
      resources :comments, except: [ :index ]
    end
    resources :comments, only: [ :index ]
  end

  #get '/users/:id/edit_schedule' =>'users#edit_schedule', as: :edit_schedule
  #patch '/users/:id/edit_schedule'=>'users#edit_schedule'

  resources :reviews, only: [ :index ]
  resources :events, only: [ :index ]
  # resources :comments, only: [ :index ]

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  EVENT_IMAGE = { "Team vs. Team イベント" =>
  "https://cdn.discordapp.com/attachments/727904622114635839/783966728245477406/never_play_alone_u7_goodbye.border.png",
  "普通のイベント" =>
  "https://cdn.discordapp.com/attachments/727904622114635839/822258963705757696/u47dc8si4u841.jpg",
  "普通のイベント２" =>
  "https://cdn.discordapp.com/attachments/727904622114635839/824229893285347388/A_Flanked_Garrison.jpg",
  "夜イベント" =>
  "https://cdn.discordapp.com/attachments/727904622114635839/824229893285347388/A_Flanked_Garrison.jpghttps://cdn.discordapp.com/attachments/727904622114635839/823625438622515220/HighresScreenshot00127a.jpg",
  "夜イベント２" =>
  "https://cdn.discordapp.com/attachments/727904622114635839/824974036064927774/HighresScreenshot00133a.png",
  "訓練" => "https://i.imgur.com/EgbDqtd.png",
  "訓練2" => "https://i.imgur.com/age8Jq0.png",
  "Admin イベント" => "https://cdn.discordapp.com/attachments/727904622114635839/748889640009990174/Hell_let_loose_HR.png" }

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_user, only: [:new, :create, :destroy]
  def index
    @events = policy_scope(Event)
    @event_image = Event::EVENT_IMAGE["Team vs. Team イベント"]
  end

  def new
    @event = Event.new
    authorize @event
  end

  def create
    @event = Event.new(event_params)
    @event.user = @user
    authorize @event
    if @event.save
      # sleep(1.5)
      sent_event_discord(@event.name, @event.description, @event.day, @event.start_time, @event.end_time)
      redirect_to events_path
    else
      redirect_to events_path, notice: "Please try again"
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    authorize @event
    redirect_to events_path
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end

  def event_params
    params.require(:event).permit(:name, :description, :day, :start_time, :end_time)
  end

  WEBHOOK_URL = ENV["DISCORDS"]

  def sent_event_discord(event_name, description, day, start_time, end_time)
    require 'discordrb/webhooks'

    client = Discordrb::Webhooks::Client.new(url: ENV["DISCORDS"])
    client.execute do |builder|
      builder.content = "イベント"
      builder.add_embed do |embed|
        embed.title = event_name
        embed.color = 16_056_575
        embed.url = "https://hlsl-jp.com/"
        # change LINK to real URL later!!!
        embed.description = "#{description}!"
        embed.add_field(name: 'Day', value: day, inline: true)
        embed.add_field(name: 'Time', value: "#{start_time.strftime('%H:%M')} - #{end_time.strftime('%H:%M')}", inline: true)
        embed.image = Discordrb::Webhooks::EmbedImage.new(url: Event::EVENT_IMAGE[event_name])
        embed.timestamp = Time.now
      end
    end
  end
end

app/views/events/_form.html.erb
<div class="row">
  <div class="col-lg-4 col-md-6 ml-auto mr-auto">
    <%= simple_form_for [ @user, @event ] do |f| %>
        <%= f.input :name, label: "イベント", collection: ["Team vs. Team イベント", "普通のイベント", "普通のイベント２", "夜イベント", "夜イベント２", "訓練", "訓練2", "Admin イベント"] %>
        <%= f.input :description, label: "内容" %>
        <%= f.input :day, as: :date, html5: true, label: "日" %>
        <%= f.input :start_time, as: :time, html5: true, label: "スタート時間" %>
        <%= f.input :end_time, as: :time, html5: true, label: "終了時間" %>
        <%# <%= f.input :XZY, as: :file %>
        <%= f.submit "確定" %>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<% if current_user.admin? %>
<h1>
  イベント
</h1>
<div>
  <p>
    <% unless current_user.nil? %>
      <% if current_user.admin? %>
        <%= link_to "新イベント作成", new_user_event_path(current_user.id), style: 'background-color: red; color: white;' %>
      <% end %>
    <% end %>
  </p>
</div>
<div class="topics">
  <% @events.order(created_at: :desc).each do |event| %>
    <div class="topic">
        <h4 class="title"><%= event.name %></h4>
        <p>内容: <%= event.description %></p>
        <p>日: <%= event.day.strftime("%d %b %Y") %></p>
        <p>スタート時間: <%= event.start_time.strftime("%H:%M") %></p>
        <p>終了時間: <%= event.end_time.strftime("%H:%M") %></p>
        <p>担当者: <%= event.user.username %></p>
        <p><%= time_ago_in_words(event.created_at)%>前に発表した</p>
        <%#= image_tag event_image %>
        <% unless current_user.nil? %>
            <% if event.user == current_user || current_user.admin? %>
                <%= link_to "消す", user_event_path(event.user.id, event), method: :delete, data: { confirm: '本当に消したいですか？' }%>
            <% end %>
        <% end %>
    </div>
  <% end %>
</div>
<% else %>
  <h1>アクセスは管理人のみ</h1>
  <h3>登録したメンバーは公開発表予定</h3>
  <%= image_tag "building3low.png" %>
<% end %>

app/views/events/new.html.erb
<%= render 'form' %>