config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/pages/news' =>'pages#news'
  get '/pages/aboutus' =>'pages#aboutus'
  get '/pages/contact' =>'pages#contact'
  get '/pages/disclaimer' =>'pages#disclaimer'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, except: [ :delete ] do
    resources :events, except: [ :index ]
    resources :reviews, except: [ :index ] do
      resources :comments, except: [ :index ]
    end
    resources :comments, only: [ :index ]
  end

  #get '/users/:id/edit_schedule' =>'users#edit_schedule', as: :edit_schedule
  #patch '/users/:id/edit_schedule'=>'users#edit_schedule'

  resources :reviews, only: [ :index ]
  resources :events, only: [ :index ]
  # resources :comments, only: [ :index ]

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_user, only: [ :new, :create, :update, :edit, :destroy ]
  skip_before_action :authenticate_user!, only: :index

  def index
    # @reviews = Review.all
    @reviews = policy_scope(Review)
  end

  def show
    @review = Review.find(params[:id])
    authorize @review
  end

  def new
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    #@owner = @user
    # @review.user_id = (params[:user_id])
    @review.user = @user
    authorize @review
    if @review.save
      redirect_to reviews_path, notice: 'Topic Added!'
    else
      render :new, notice: "Please try again"
    end
  end

  def edit
    @review = Review.find(params[:id])
    authorize @review
  end

  def update
    @review = Review.find(params[:id])
    authorize @review
    @review.update(review_params)
    redirect_to review_path(@review)
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    authorize @review
    redirect_to reviews_path
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end

  def review_params
    params.require(:review).permit(:content, :topic, photos: [])
    # params.require(:review).permit(:rating, :content, :reviewer_id, :user_id)
  end
end

app/views/reviews/_form.html.erb
<div class="row">
  <div class="col-lg-4 col-md-6 ml-auto mr-auto">
    <%= simple_form_for [ @user, @review ] do |f| %>
        <%= f.input :topic, label: "話題" %>
        <%= f.input :content, label: "内容" %>
        <%= f.input :photos, as: :file, input_html: { multiple: true }, label: "写真アップロード" %>
        <%= f.submit "確定" %>
    <% end %>
  </div>
</div>

app/views/reviews/index.html.erb
<h1 class="top-bar">フォーラム</h1>
<% if current_user.nil? %>
    <h1>近日公開</h1>
<% else %>
    <% if current_user.admin? || current_user == nil %>
    <div>
        <% unless current_user.nil? %>
        <p>
            <%= link_to "新しいトピックの作成", new_user_review_path(current_user.id), style: 'color: red;' %>
        </p>
        <% end %>
    </div>
    <div class="col-12 d-flex flex-column justify-content-center align-items-center">
        <div>
            <table>
                <tr>
                    <th>タイトル</th>
                    <th>視聴者数</th>
                    <%# add kaminari/impressionist %>
                    <th>作家</th>
                    <th>発表日</th>
                    <th>コメント数</th>
                </tr>
                <%# in a row but need column %>
                <div class="topics">
                <% @reviews.order(created_at: :desc).each do |review| %>
                    <div class="topic">
                        <h4 class="title"><%= link_to review.topic, user_review_path(review.user.id, review) %></h4>
                        <td><%= review.content %></td>
                        <td><%= review.user.username %></td>
                        <td><%= time_ago_in_words(review.created_at)%>前に発表した</td>
                        <td>コメント数: <%= review.comments.count %></td>
                    </div>
                    <td>
                        <% unless current_user.nil? %>
                            <% if review.user == current_user || current_user.admin? %>
                            <%= link_to "消す", user_review_path(review.user.id, review), method: :delete, data: { confirm: '本当に消したいですか？' }%>
                            <% end %>
                        <% end %>
                    </td>
                    <% end %>
                </div>
                </tr>
            </table>
        </div>
        <div class="topics">
        <% @reviews.order(created_at: :desc).each do |review| %>
            <div class="topic">
                <h4 class="title"><%= link_to review.topic, user_review_path(review.user.id, review) %></h4>
                <p><%= review.content %></p>
                <p><%= review.user.username %></p>
                <p><%= time_ago_in_words(review.created_at)%>前に発表した</p>
                <p>コメント数: <%= review.comments.count %></p>
            </div>
        <% end %>
        </div>
    </div>
    <% else %>
        <h1>近日公開</h1>
        <%= image_tag "building3low.png" %>
    <% end %>
<% end %>

app/views/reviews/new.html.erb
<% unless current_user.nil? %>
    <%= render 'form' %>
<% end %>

app/views/reviews/show.html.erb
<h1><%= @review.topic %></h1>
<p><%= @review.content %></p>
<p><%= @review.user.username %></p>
<p><%= time_ago_in_words(@review.created_at)%>前に発表した</p>
<p>here should go comments</p>

    <% @review.photos.each do |photo| %>
        <% if !photo.nil? %>
            <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
        <% end %>
    <% end %>
<% @review.comments.order(created_at: :desc).each do |comment| %>
    <p><%= comment.reply %></p>
<% end %>
<p>
    <%= link_to "Reply", new_user_review_comment_path(current_user.id, @review.id), style: 'color: red;' %>
</p>